# Generated by Django 3.0.7 on 2020-09-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberSourceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
